### ISSUE TITLE
The version number via composer is "dev-main" instead of "1.0.3"

### ISSUE THREAD

**Issue by mikkorantalainen** [hugerte/hugerte#30]
## 📝 Provide detailed reproduction steps (if any)
1. `composer install hugerte/hugerte`

### ✔️ Expected result
This should install the latest published version (`1.0.3` as I'm writing this).

### ❌ Actual result
The available version is called `dev-main` instead. Installing that version results in binary identical results to version `1.0.3` so I consider this being just a metadata issue in the composer distribution.

I'd guess that whatever method was used to publish the code to Packagist had version number accidentally set to `dev-main` instead of `1.0.3`.

**Comment by carlosmintfan** [comment]
Thanks, so I must tag every commit with a version, the version in composer.json is not enough. Fixed!
